export default [
  {
    id: "1",
    user: "joshan",
    club: "Apex Sports Club",
    title: "Futsal touranament",
    description:
      "Track your location with our app and get ready to get picked up from your friends, colleague or teachers",
    location: "Apex College",
    eventDate: "2021-12-01 12:00 PM",
    dateCreated: "2021-12-01 12:00 PM",
  },
  {
    id: "2",
    user: "joshan",
    club: "Apex IT Club",
    title: "Dota game competition",
    description:
      "Explores places where you get to meet and greet new people around your college",
    location: "Mid Baneshwor, Ace College",
    eventDate: "2021-12-01 12:00 PM",
    dateCreated: "2021-12-01 12:00 PM",
  },
  {
    id: "3",
    user: "joshan",
    club: "Apex Music and Dance Club",
    title: "Dancing competition for all bachelors",
    description:
      "Confirm your rider ensuring they can safely take you to your destination",
    location: "Thamel",
    eventDate: "2021-12-01 12:00 PM",
    dateCreated: "2021-12-01 12:00 PM",
  },
  {
    id: "4",
    user: "joshan",
    club: "Apex Heat Club",
    title: "Heat",
    description: "You can easily app using credit that you have in your wallet",
    location: "Durbarmarg",
    eventDate: "2021-12-01 12:00 PM",
    dateCreated: "2021-12-01 12:00 PM",
  },
  {
    id: "5",
    user: "joshan",
    club: "Apex Media Club",
    title: "Dacne and win",
    description: "You can easily app using credit that you have in your wallet",
    location: "Durbarmarg",
    eventDate: "2021-12-01 12:00 PM",
    dateCreated: "2021-12-01 12:00 PM",
  },
];
